### ISSUE TITLE
Initialise phoenix project

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/library#2]
We'll need to generate a phoenix project.

Potential dependencies:

Dev/test
- credo (by us)
- pre_commit (also by us :heart:)
- coveralls
- envy (for environment variables)

Prod
- elixir_auth_github

**Comment by ZooeyMiller** [comment]
+ [ ] set up travis

**Comment by ZooeyMiller** [comment]
Since we're also setting up travis, we're getting our initial coverage up to 100% which will take some extra time, hence the new time label.
