### ISSUE TITLE
Create button component to do different things depending on state

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/library#21]
We have a button on the book component, this button should do different things depending on the state of the book/application:

+ If the book is in the library and is not on loan then it should say "Borrow book"
+ If it is in the library but is on loan it should say "Join queue"
+ If it is in the library and is on loan to the user viewing it it should say "Return"
+ If it is not in the library and the user is not an admin it should say "Request book"
+ If it is not in the library and the user is an admin it should say "Add book"

The buttons should of course have relevant actions which fulfil the actions represented on them in text.

**Comment by finnhodgkin** [comment]
This was definitely under-estimated. I've got the base functionality in but no tests/docs.

**Comment by finnhodgkin** [comment]
Because #32 isn't in yet I've left the `get_user` and `admin?` functions with hard-coded values.

Will have to come back to this code whenever we add a new feature utilising one of the states (Request, Join queue, etc.).
