### ISSUE TITLE
Add login

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/library#32]
We need to set up authentication so that protected routes are possible (admin only routes), certain requests are only available to certain users (only the user who has checked out a book can check it back in).

This will involve using the https://github.com/dwyl/elixir-auth-github module and setting up a new app on OAuth.

Users as standard will not be admins, but we will manually configure an admin user. 

### Acceptance criteria
+ The home page can be viewed by anyone, but they cannot do anything with any of the books if they are not logged in.
+ Users can log in with github, and their information is saved in the database
+ Check if they are in the dwyl organisation during sign up, and if they are not give them an error that they cannot partake in the library. #41

**Comment by ZooeyMiller** [comment]
Forgot to remove `in-progress` last night :bowing_man: I stopped at 18:00 and am starting again now.

**Comment by ZooeyMiller** [comment]
I'm having some trouble dealing with getting organisations from the github api, even with no authentication `https://api.github.com/users/nelsonic/orgs` returns an array of organizations, but `https://api.github.com/users/zooeymiller/orgs` does not. I've even tried to do so with `zooeymiller` with an access_token and it's still an empty array.

I'm going to spend 25 minutes on trying to find a solution for this, if I can't find one, for the sake of #38 I will bypass this aspect of the acceptance criteria and raise it as a separate issue.

**Comment by ZooeyMiller** [comment]
:sweat_smile: turns out it's because I was using the wrong url. `/users/<username>/orgs` is for getting info from github api without OAuth access, when you have an access token for a user it's just `/user/orgs` with the access token set on the user. 

There is however a problem in the dwyl has to authorise any user individually to have read access to the fact that they are a member, which means at the moment it's unrealistic to have users who are not shown as a member of dwyl to log in. I will raise this as a separate issue and link it in the top comment.

**Comment by finnhodgkin** [comment]
I'm not sure about the flash message for a successful login "Added to db succesfully". 

I think "Welcome #{name}" or "Logged in" would be more appropriate.
