### ISSUE TITLE
run "mix deps.get" before "npm i"

### ISSUE THREAD

**Issue by SimonLab** [dwyl/library#33]
On the instruction on how to run ```library``` on locally:
![image](https://user-images.githubusercontent.com/6057298/31731076-d04bfa0c-b42b-11e7-97fb-c93ec432c6d9.png)
I think we need to run ```mix deps.get``` before trying to install the nodejs package, otherwise I've got this error:
![image](https://user-images.githubusercontent.com/6057298/31731128-f1d5f8c6-b42b-11e7-97ef-8d951098aec3.png)

**Comment by SimonLab** [comment]
Looks good :+1: 
![image](https://user-images.githubusercontent.com/6057298/31810221-d9d587f8-b572-11e7-9e20-0ddb31a958fb.png)

Thanks for the update @ZooeyMiller 

fixed with #36 
Not sure if you are adding more info on the readme, the issue is still "in-progress" but I think it's done and the labels just need to be updated. Happy for you to close the issue as I already tested it.

**Comment by ZooeyMiller** [comment]
I just forgot to remove the in-progress label :bowing_man: 
Closing, feel free to re-open if you end up feeling this needs extra work!
