### ISSUE TITLE
The database isn't seeded on Heroku

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/library#40]
We're getting an `Internal server error` on Heroku because the migrations haven't been run. I think it just needs the procfile to have Ecto.migrate as well as phx.server.

**Comment by finnhodgkin** [comment]
There's a pending OAuth transfer to dwyl that needs to be accepted before the live app can be tested.

**Comment by iteles** [comment]
@finnhodgkin These are the ones under dwyl's ownership as of now:

<img width="621" alt="screen shot 2017-10-30 at 13 18 35" src="https://user-images.githubusercontent.com/4185328/32173194-0e187272-bd76-11e7-8530-7f55fe8e5030.png">

**Comment by ZooeyMiller** [comment]
The app seems to be working properly on heroku now, is this issue solved? @finnhodgkin

**Comment by finnhodgkin** [comment]
Yep @ZooeyMiller. Closing
