### ISSUE TITLE
dwyl needs to give access to the OAuth app for data about members

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/library#41]
As noted in https://github.com/dwyl/library/issues/32#issuecomment-338159521 when we set up the app for the live version, we will need to set up an OAuth app in github, this app will need to be granted read access to the organisation's members by dwyl. 

I think perhaps if the OAuth app is made by dwyl then the permissions won't need to be granted? Nonetheless, it's something we will need to deal with when we create the production app.

**Comment by iteles** [comment]
Is there a way to pass ownership of the app over to dwyl? That might also resolve the issue.

**Comment by ZooeyMiller** [comment]
@iteles I've requested the transfer of the in development OAuth app to dwyl, so once a dwyl owner approves this we can see if it fixes this issue.

**Comment by iteles** [comment]
@ZooeyMiller Just seen the request, done! 👍

**Comment by ZooeyMiller** [comment]
Works perfectly! Thanks.
