### ISSUE TITLE
Set up an admin user on heroku database

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/library#67]
We need to set up an admin user on the heroku database so that we can add some books to the database. 

This will allow us to check that #26 #27 #29 are working properly on heroku. 

I would happily do this, but I would need to connect to the heroku database to do so and I don't have access to it to get the databse url, could someone send me it or give me access?

**Comment by finnhodgkin** [comment]
Which email do you use for heroku @ZooeyMiller? If you gitter me it I'll add you as a collaborator asap :+1:

**Comment by ZooeyMiller** [comment]
I've set myself up as an admin now, so this is sorted :+1: 

Will set you up as an admin as soon as you've logged in once @iteles then will close this issue.

**Comment by ZooeyMiller** [comment]
@iteles is now set up as an admin.
